server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          #search-locations: classpath:/configurations  if the configuration files are under /resources/configurations folder
          search-locations: ${HOME}/config-repo/spring-cloud-config
  profiles:
    active: native