spring:
  cloud:
    config:
      server:
        native:
          #search-locations: classpath:/configurations  if the configuration files are under /resources/configurations folder
          search-locations: ${HOME}/config-repo/spring-cloud-config
  profiles:
    active: native
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    web: debug
    root: debug
